/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as CatalogRouteRouteImport } from './routes/catalog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentIndexRouteImport } from './routes/shipment/index'
import { Route as ProductionLineIndexRouteImport } from './routes/production-line/index'
import { Route as GroupIndexRouteImport } from './routes/group/index'
import { Route as ConfigTransformIndexRouteImport } from './routes/config-transform/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as GroupChar123GroupIdChar125RouteRouteImport } from './routes/group/{-$groupId}/route'
import { Route as CatalogDocsIndexRouteImport } from './routes/catalog/docs/index'
import { Route as CatalogDocsSlugRouteImport } from './routes/catalog/docs/$slug'
import { Route as GroupChar123GroupIdChar125PriceWatchIndexRouteImport } from './routes/group/{-$groupId}/price-watch/index'
import { Route as GroupChar123GroupIdChar125PlanIndexRouteImport } from './routes/group/{-$groupId}/plan/index'
import { Route as GroupChar123GroupIdChar125MembersIndexRouteImport } from './routes/group/{-$groupId}/members/index'
import { Route as GroupChar123GroupIdChar125ContractsIndexRouteImport } from './routes/group/{-$groupId}/contracts/index'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRouteRoute = CatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentIndexRoute = ShipmentIndexRouteImport.update({
  id: '/shipment/',
  path: '/shipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionLineIndexRoute = ProductionLineIndexRouteImport.update({
  id: '/production-line/',
  path: '/production-line/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/group/',
  path: '/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigTransformIndexRoute = ConfigTransformIndexRouteImport.update({
  id: '/config-transform/',
  path: '/config-transform/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const GroupChar123GroupIdChar125RouteRoute =
  GroupChar123GroupIdChar125RouteRouteImport.update({
    id: '/group/{-$groupId}',
    path: '/group/{-$groupId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogDocsIndexRoute = CatalogDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const CatalogDocsSlugRoute = CatalogDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const GroupChar123GroupIdChar125PriceWatchIndexRoute =
  GroupChar123GroupIdChar125PriceWatchIndexRouteImport.update({
    id: '/price-watch/',
    path: '/price-watch/',
    getParentRoute: () => GroupChar123GroupIdChar125RouteRoute,
  } as any)
const GroupChar123GroupIdChar125PlanIndexRoute =
  GroupChar123GroupIdChar125PlanIndexRouteImport.update({
    id: '/plan/',
    path: '/plan/',
    getParentRoute: () => GroupChar123GroupIdChar125RouteRoute,
  } as any)
const GroupChar123GroupIdChar125MembersIndexRoute =
  GroupChar123GroupIdChar125MembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => GroupChar123GroupIdChar125RouteRoute,
  } as any)
const GroupChar123GroupIdChar125ContractsIndexRoute =
  GroupChar123GroupIdChar125ContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => GroupChar123GroupIdChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/group/{-$groupId}': typeof GroupChar123GroupIdChar125RouteRouteWithChildren
  '/catalog/': typeof CatalogIndexRoute
  '/config-transform/': typeof ConfigTransformIndexRoute
  '/group/': typeof GroupIndexRoute
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
  '/catalog/docs/$slug': typeof CatalogDocsSlugRoute
  '/catalog/docs/': typeof CatalogDocsIndexRoute
  '/group/{-$groupId}/contracts/': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members/': typeof GroupChar123GroupIdChar125MembersIndexRoute
  '/group/{-$groupId}/plan/': typeof GroupChar123GroupIdChar125PlanIndexRoute
  '/group/{-$groupId}/price-watch/': typeof GroupChar123GroupIdChar125PriceWatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/group/{-$groupId}': typeof GroupChar123GroupIdChar125RouteRouteWithChildren
  '/catalog': typeof CatalogIndexRoute
  '/config-transform': typeof ConfigTransformIndexRoute
  '/group': typeof GroupIndexRoute
  '/production-line': typeof ProductionLineIndexRoute
  '/shipment': typeof ShipmentIndexRoute
  '/catalog/docs/$slug': typeof CatalogDocsSlugRoute
  '/catalog/docs': typeof CatalogDocsIndexRoute
  '/group/{-$groupId}/contracts': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members': typeof GroupChar123GroupIdChar125MembersIndexRoute
  '/group/{-$groupId}/plan': typeof GroupChar123GroupIdChar125PlanIndexRoute
  '/group/{-$groupId}/price-watch': typeof GroupChar123GroupIdChar125PriceWatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/group/{-$groupId}': typeof GroupChar123GroupIdChar125RouteRouteWithChildren
  '/catalog/': typeof CatalogIndexRoute
  '/config-transform/': typeof ConfigTransformIndexRoute
  '/group/': typeof GroupIndexRoute
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
  '/catalog/docs/$slug': typeof CatalogDocsSlugRoute
  '/catalog/docs/': typeof CatalogDocsIndexRoute
  '/group/{-$groupId}/contracts/': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members/': typeof GroupChar123GroupIdChar125MembersIndexRoute
  '/group/{-$groupId}/plan/': typeof GroupChar123GroupIdChar125PlanIndexRoute
  '/group/{-$groupId}/price-watch/': typeof GroupChar123GroupIdChar125PriceWatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/error'
    | '/group/{-$groupId}'
    | '/catalog/'
    | '/config-transform/'
    | '/group/'
    | '/production-line/'
    | '/shipment/'
    | '/catalog/docs/$slug'
    | '/catalog/docs/'
    | '/group/{-$groupId}/contracts/'
    | '/group/{-$groupId}/members/'
    | '/group/{-$groupId}/plan/'
    | '/group/{-$groupId}/price-watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/group/{-$groupId}'
    | '/catalog'
    | '/config-transform'
    | '/group'
    | '/production-line'
    | '/shipment'
    | '/catalog/docs/$slug'
    | '/catalog/docs'
    | '/group/{-$groupId}/contracts'
    | '/group/{-$groupId}/members'
    | '/group/{-$groupId}/plan'
    | '/group/{-$groupId}/price-watch'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/error'
    | '/group/{-$groupId}'
    | '/catalog/'
    | '/config-transform/'
    | '/group/'
    | '/production-line/'
    | '/shipment/'
    | '/catalog/docs/$slug'
    | '/catalog/docs/'
    | '/group/{-$groupId}/contracts/'
    | '/group/{-$groupId}/members/'
    | '/group/{-$groupId}/plan/'
    | '/group/{-$groupId}/price-watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  GroupChar123GroupIdChar125RouteRoute: typeof GroupChar123GroupIdChar125RouteRouteWithChildren
  ConfigTransformIndexRoute: typeof ConfigTransformIndexRoute
  GroupIndexRoute: typeof GroupIndexRoute
  ProductionLineIndexRoute: typeof ProductionLineIndexRoute
  ShipmentIndexRoute: typeof ShipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/': {
      id: '/shipment/'
      path: '/shipment'
      fullPath: '/shipment/'
      preLoaderRoute: typeof ShipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-line/': {
      id: '/production-line/'
      path: '/production-line'
      fullPath: '/production-line/'
      preLoaderRoute: typeof ProductionLineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/group'
      fullPath: '/group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-transform/': {
      id: '/config-transform/'
      path: '/config-transform'
      fullPath: '/config-transform/'
      preLoaderRoute: typeof ConfigTransformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/group/{-$groupId}': {
      id: '/group/{-$groupId}'
      path: '/group/{-$groupId}'
      fullPath: '/group/{-$groupId}'
      preLoaderRoute: typeof GroupChar123GroupIdChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/docs/': {
      id: '/catalog/docs/'
      path: '/docs'
      fullPath: '/catalog/docs/'
      preLoaderRoute: typeof CatalogDocsIndexRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/docs/$slug': {
      id: '/catalog/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/catalog/docs/$slug'
      preLoaderRoute: typeof CatalogDocsSlugRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/group/{-$groupId}/price-watch/': {
      id: '/group/{-$groupId}/price-watch/'
      path: '/price-watch'
      fullPath: '/group/{-$groupId}/price-watch/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125PriceWatchIndexRouteImport
      parentRoute: typeof GroupChar123GroupIdChar125RouteRoute
    }
    '/group/{-$groupId}/plan/': {
      id: '/group/{-$groupId}/plan/'
      path: '/plan'
      fullPath: '/group/{-$groupId}/plan/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125PlanIndexRouteImport
      parentRoute: typeof GroupChar123GroupIdChar125RouteRoute
    }
    '/group/{-$groupId}/members/': {
      id: '/group/{-$groupId}/members/'
      path: '/members'
      fullPath: '/group/{-$groupId}/members/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125MembersIndexRouteImport
      parentRoute: typeof GroupChar123GroupIdChar125RouteRoute
    }
    '/group/{-$groupId}/contracts/': {
      id: '/group/{-$groupId}/contracts/'
      path: '/contracts'
      fullPath: '/group/{-$groupId}/contracts/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125ContractsIndexRouteImport
      parentRoute: typeof GroupChar123GroupIdChar125RouteRoute
    }
  }
}

interface CatalogRouteRouteChildren {
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogDocsSlugRoute: typeof CatalogDocsSlugRoute
  CatalogDocsIndexRoute: typeof CatalogDocsIndexRoute
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogDocsSlugRoute: CatalogDocsSlugRoute,
  CatalogDocsIndexRoute: CatalogDocsIndexRoute,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

interface GroupChar123GroupIdChar125RouteRouteChildren {
  GroupChar123GroupIdChar125ContractsIndexRoute: typeof GroupChar123GroupIdChar125ContractsIndexRoute
  GroupChar123GroupIdChar125MembersIndexRoute: typeof GroupChar123GroupIdChar125MembersIndexRoute
  GroupChar123GroupIdChar125PlanIndexRoute: typeof GroupChar123GroupIdChar125PlanIndexRoute
  GroupChar123GroupIdChar125PriceWatchIndexRoute: typeof GroupChar123GroupIdChar125PriceWatchIndexRoute
}

const GroupChar123GroupIdChar125RouteRouteChildren: GroupChar123GroupIdChar125RouteRouteChildren =
  {
    GroupChar123GroupIdChar125ContractsIndexRoute:
      GroupChar123GroupIdChar125ContractsIndexRoute,
    GroupChar123GroupIdChar125MembersIndexRoute:
      GroupChar123GroupIdChar125MembersIndexRoute,
    GroupChar123GroupIdChar125PlanIndexRoute:
      GroupChar123GroupIdChar125PlanIndexRoute,
    GroupChar123GroupIdChar125PriceWatchIndexRoute:
      GroupChar123GroupIdChar125PriceWatchIndexRoute,
  }

const GroupChar123GroupIdChar125RouteRouteWithChildren =
  GroupChar123GroupIdChar125RouteRoute._addFileChildren(
    GroupChar123GroupIdChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  GroupChar123GroupIdChar125RouteRoute:
    GroupChar123GroupIdChar125RouteRouteWithChildren,
  ConfigTransformIndexRoute: ConfigTransformIndexRoute,
  GroupIndexRoute: GroupIndexRoute,
  ProductionLineIndexRoute: ProductionLineIndexRoute,
  ShipmentIndexRoute: ShipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
