/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentIndexRouteImport } from './routes/shipment/index'
import { Route as ProductionLineIndexRouteImport } from './routes/production-line/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentIndexRoute = ShipmentIndexRouteImport.update({
  id: '/shipment/',
  path: '/shipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionLineIndexRoute = ProductionLineIndexRouteImport.update({
  id: '/production-line/',
  path: '/production-line/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/production-line': typeof ProductionLineIndexRoute
  '/shipment': typeof ShipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/production-line/' | '/shipment/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/production-line' | '/shipment'
  id: '__root__' | '/' | '/production-line/' | '/shipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductionLineIndexRoute: typeof ProductionLineIndexRoute
  ShipmentIndexRoute: typeof ShipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/': {
      id: '/shipment/'
      path: '/shipment'
      fullPath: '/shipment/'
      preLoaderRoute: typeof ShipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-line/': {
      id: '/production-line/'
      path: '/production-line'
      fullPath: '/production-line/'
      preLoaderRoute: typeof ProductionLineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductionLineIndexRoute: ProductionLineIndexRoute,
  ShipmentIndexRoute: ShipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
